export const formStyles = {
  container: {
    padding: "32px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    marginBottom: "24px",
  },
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: "var(--text-secondary)",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: "500",
    marginBottom: "16px",
    transition: "color 0.2s",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "var(--text-primary)",
    margin: 0,
    fontFamily: "var(--font-serif)",
  },
  error: {
    backgroundColor: "var(--color-danger-light)",
    color: "var(--color-danger)",
    padding: "16px",
    borderRadius: "var(--border-radius-sm)",
    marginBottom: "24px",
    fontSize: "14px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "24px",
    alignItems: "start",
  },
  mainCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  sideCol: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    position: "sticky",
    top: "24px",
  },
  card: {
    backgroundColor: "var(--bg-primary)",
    borderRadius: "var(--border-radius-md)",
    border: "1px solid var(--border-color)",
    padding: "24px",
  },
  cardTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "var(--text-primary)",
    marginBottom: "20px",
    paddingBottom: "12px",
    borderBottom: "1px solid var(--border-color)",
  },
  formGroup: {
    marginBottom: "16px",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: "var(--text-secondary)",
    marginBottom: "8px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: "14px",
    border: "1px solid var(--border-color)",
    borderRadius: "var(--border-radius-sm)",
    backgroundColor: "var(--bg-primary)",
    color: "var(--text-primary)",
    outline: "none",
    transition: "border-color 0.2s",
  },
  checkboxGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
    fontSize: "14px",
    color: "var(--text-primary)",
  },
  submitBtn: {
    width: "100%",
    padding: "12px",
    backgroundColor: "var(--primary-brand)",
    color: "#fff",
    border: "none",
    borderRadius: "var(--border-radius-sm)",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "16px",
    transition: "background-color 0.2s",
  },
  uploadArea: {
    position: "relative",
    border: "2px dashed var(--border-color)",
    borderRadius: "var(--border-radius-sm)",
    padding: "24px",
    textAlign: "center",
    backgroundColor: "var(--bg-secondary)",
    cursor: "pointer",
    transition: "border-color 0.2s",
  },
  fileInput: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    opacity: 0,
    cursor: "pointer",
  },
  uploadLabel: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-secondary)",
    fontSize: "13px",
  },
  galleryPreview: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "12px",
  },
  galleryItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    backgroundColor: "var(--bg-secondary)",
    border: "1px solid var(--border-color)",
    borderRadius: "4px",
  },
  removeBtn: {
    background: "transparent",
    border: "none",
    color: "var(--color-danger)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: "4px",
  },
  currentImage: {
    marginTop: "12px",
    padding: "12px",
    backgroundColor: "var(--bg-secondary)",
    borderRadius: "4px",
  },
  previewImg: {
    width: "80px",
    height: "80px",
    objectFit: "cover",
    borderRadius: "4px",
    border: "1px solid var(--border-color)",
  },
  actionBtn: {
    width: "100%",
    padding: "10px",
    backgroundColor: "var(--bg-secondary)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-color)",
    borderRadius: "var(--border-radius-sm)",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "12px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  cancelBtn: {
    width: "100%",
    padding: "10px",
    backgroundColor: "transparent",
    color: "var(--color-danger)",
    border: "1px solid var(--color-danger)",
    borderRadius: "var(--border-radius-sm)",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    marginTop: "8px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  }
};
